spring:
  profiles:
    default: local

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: member-wj-files

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: INFO